!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - clip_range
    - 0.3
  - - ent_coef
    - 0.09060256206365265
  - - env_wrapper
    - - src.main.rl.wrapper.action_wrapper3.ActionSpaceOption3Wrapper
      - src.main.rl.wrapper.obs_wrapper5.ObservationOption5Wrapper
      - src.main.rl.wrapper.reward_wrapper3.RewardOption3Wrapper
  - - gae_lambda
    - 0.8
  - - gamma
    - 0.99
  - - learning_rate
    - 0.001216718814675719
  - - max_grad_norm
    - 0.3
  - - n_envs
    - 8
  - - n_epochs
    - 5
  - - n_steps
    - 2048
  - - n_timesteps
    - 200000
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(activation_fn=nn.Tanh)
  - - vf_coef
    - 0.5399983502788293
